// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Assets.Client.Models
{
    using Lykke.Service;
    using Lykke.Service.Assets;
    using Lykke.Service.Assets.Client;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GetAssetDescriptionsRequestModel
    {
        /// <summary>
        /// Initializes a new instance of the GetAssetDescriptionsRequestModel
        /// class.
        /// </summary>
        public GetAssetDescriptionsRequestModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetAssetDescriptionsRequestModel
        /// class.
        /// </summary>
        public GetAssetDescriptionsRequestModel(IList<string> ids = default(IList<string>))
        {
            Ids = ids;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Ids")]
        public IList<string> Ids { get; set; }

    }
}
