// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Assets.Client
{
    using Lykke.Service;
    using Lykke.Service.Assets;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Assetsservice.
    /// </summary>
    public static partial class AssetsserviceExtensions
    {
            /// <summary>
            /// Forcibly updates asset pairs cache
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void UpdateAssetPairsCache(this IAssetsservice operations)
            {
                operations.UpdateAssetPairsCacheAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Forcibly updates asset pairs cache
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task UpdateAssetPairsCacheAsync(this IAssetsservice operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.UpdateAssetPairsCacheWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Returns asset pair by ID
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='assetPairId'>
            /// Asset pair ID
            /// </param>
            public static object GetAssetPair(this IAssetsservice operations, string assetPairId)
            {
                return operations.GetAssetPairAsync(assetPairId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns asset pair by ID
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='assetPairId'>
            /// Asset pair ID
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetAssetPairAsync(this IAssetsservice operations, string assetPairId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAssetPairWithHttpMessagesAsync(assetPairId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Returns all asset pairs
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<AssetPairResponseModel> GetAssetPairs(this IAssetsservice operations)
            {
                return operations.GetAssetPairsAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns all asset pairs
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<AssetPairResponseModel>> GetAssetPairsAsync(this IAssetsservice operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAssetPairsWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Forcibly updates assets cache
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void UpdateAssetsCache(this IAssetsservice operations)
            {
                operations.UpdateAssetsCacheAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Forcibly updates assets cache
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task UpdateAssetsCacheAsync(this IAssetsservice operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.UpdateAssetsCacheWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Returns asset by ID
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='assetId'>
            /// Asset ID
            /// </param>
            public static object GetAsset(this IAssetsservice operations, string assetId)
            {
                return operations.GetAssetAsync(assetId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns asset by ID
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='assetId'>
            /// Asset ID
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetAssetAsync(this IAssetsservice operations, string assetId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAssetWithHttpMessagesAsync(assetId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Returns all assets
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<AssetResponseModel> GetAssets(this IAssetsservice operations)
            {
                return operations.GetAssetsAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns all assets
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<AssetResponseModel>> GetAssetsAsync(this IAssetsservice operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAssetsWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Returns asset attributes by ID
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='assetId'>
            /// Asset ID
            /// </param>
            public static AssetAttributesResponseModel GetAssetAttributes(this IAssetsservice operations, string assetId)
            {
                return operations.GetAssetAttributesAsync(assetId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns asset attributes by ID
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='assetId'>
            /// Asset ID
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<AssetAttributesResponseModel> GetAssetAttributesAsync(this IAssetsservice operations, string assetId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAssetAttributesWithHttpMessagesAsync(assetId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Returns asset attribute by asset ID and attribute key
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='assetId'>
            /// Asset ID
            /// </param>
            /// <param name='key'>
            /// Attribute key
            /// </param>
            public static AssetAttributesResponseModel GetAssetAttributeByKey(this IAssetsservice operations, string assetId, string key)
            {
                return operations.GetAssetAttributeByKeyAsync(assetId, key).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns asset attribute by asset ID and attribute key
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='assetId'>
            /// Asset ID
            /// </param>
            /// <param name='key'>
            /// Attribute key
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<AssetAttributesResponseModel> GetAssetAttributeByKeyAsync(this IAssetsservice operations, string assetId, string key, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAssetAttributeByKeyWithHttpMessagesAsync(assetId, key, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Returns asset descriptions for array of assets
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            public static AssetDescriptionsResponseModel GetAssetDescriptions(this IAssetsservice operations, GetAssetDescriptionsRequestModel request = default(GetAssetDescriptionsRequestModel))
            {
                return operations.GetAssetDescriptionsAsync(request).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns asset descriptions for array of assets
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<AssetDescriptionsResponseModel> GetAssetDescriptionsAsync(this IAssetsservice operations, GetAssetDescriptionsRequestModel request = default(GetAssetDescriptionsRequestModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAssetDescriptionsWithHttpMessagesAsync(request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Returns all asset categories
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<AssetCategoriesResponseModel> GetAssetCategories(this IAssetsservice operations)
            {
                return operations.GetAssetCategoriesAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns all asset categories
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<AssetCategoriesResponseModel>> GetAssetCategoriesAsync(this IAssetsservice operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAssetCategoriesWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Returns asset category for asset id
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='assetId'>
            /// Asset ID
            /// </param>
            public static object GetAssetCategory(this IAssetsservice operations, string assetId)
            {
                return operations.GetAssetCategoryAsync(assetId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns asset category for asset id
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='assetId'>
            /// Asset ID
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetAssetCategoryAsync(this IAssetsservice operations, string assetId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAssetCategoryWithHttpMessagesAsync(assetId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Returns all assets extended
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static AssetExtendedResponseModel GetAssetsExtended(this IAssetsservice operations)
            {
                return operations.GetAssetsExtendedAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns all assets extended
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<AssetExtendedResponseModel> GetAssetsExtendedAsync(this IAssetsservice operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAssetsExtendedWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Returns all assets extended
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='assetId'>
            /// </param>
            public static object GetAssetExtended(this IAssetsservice operations, string assetId)
            {
                return operations.GetAssetExtendedAsync(assetId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns all assets extended
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='assetId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetAssetExtendedAsync(this IAssetsservice operations, string assetId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAssetExtendedWithHttpMessagesAsync(assetId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Checks service is alive
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IsAliveResponse IsAlive(this IAssetsservice operations)
            {
                return operations.IsAliveAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Checks service is alive
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IsAliveResponse> IsAliveAsync(this IAssetsservice operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.IsAliveWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
