// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Assets.Client.Models
{
    using Lykke.Service;
    using Lykke.Service.Assets;
    using Lykke.Service.Assets.Client;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AssetDescriptionsResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the AssetDescriptionsResponseModel
        /// class.
        /// </summary>
        public AssetDescriptionsResponseModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetDescriptionsResponseModel
        /// class.
        /// </summary>
        public AssetDescriptionsResponseModel(IList<AssetExtendedInfo> descriptions = default(IList<AssetExtendedInfo>), ErrorResponse errorResponse = default(ErrorResponse))
        {
            Descriptions = descriptions;
            ErrorResponse = errorResponse;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Descriptions")]
        public IList<AssetExtendedInfo> Descriptions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorResponse")]
        public ErrorResponse ErrorResponse { get; set; }

    }
}
