// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Assets.Client.Models
{
    using Lykke.Service;
    using Lykke.Service.Assets;
    using Lykke.Service.Assets.Client;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AssetExtendedResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the AssetExtendedResponseModel class.
        /// </summary>
        public AssetExtendedResponseModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetExtendedResponseModel class.
        /// </summary>
        public AssetExtendedResponseModel(IList<AssetExtended> assets = default(IList<AssetExtended>))
        {
            Assets = assets;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Assets")]
        public IList<AssetExtended> Assets { get; set; }

    }
}
