// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Assets.Client.Models
{
    using Lykke.Service;
    using Lykke.Service.Assets;
    using Lykke.Service.Assets.Client;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AssetExtended
    {
        /// <summary>
        /// Initializes a new instance of the AssetExtended class.
        /// </summary>
        public AssetExtended()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetExtended class.
        /// </summary>
        public AssetExtended(IAsset asset = default(IAsset), IAssetDescription description = default(IAssetDescription), IAssetCategory category = default(IAssetCategory), IList<IAssetAttributesKeyValue> attributes = default(IList<IAssetAttributesKeyValue>))
        {
            Asset = asset;
            Description = description;
            Category = category;
            Attributes = attributes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public IAsset Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public IAssetDescription Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Category")]
        public IAssetCategory Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attributes")]
        public IList<IAssetAttributesKeyValue> Attributes { get; set; }

    }
}
