// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Assets.Client.Models
{
    using Lykke.Service;
    using Lykke.Service.Assets;
    using Lykke.Service.Assets.Client;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AssetAttributesResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the AssetAttributesResponseModel
        /// class.
        /// </summary>
        public AssetAttributesResponseModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetAttributesResponseModel
        /// class.
        /// </summary>
        public AssetAttributesResponseModel(string assetId = default(string), IList<IAssetAttributesKeyValue> pairs = default(IList<IAssetAttributesKeyValue>))
        {
            AssetId = assetId;
            Pairs = pairs;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Pairs")]
        public IList<IAssetAttributesKeyValue> Pairs { get; set; }

    }
}
