// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Assets.Client.Models
{
    using Lykke.Service;
    using Lykke.Service.Assets;
    using Lykke.Service.Assets.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetPairResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the AssetPairResponseModel class.
        /// </summary>
        public AssetPairResponseModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetPairResponseModel class.
        /// </summary>
        public AssetPairResponseModel(string id = default(string), string name = default(string), string baseAssetId = default(string), string quotingAssetId = default(string), int? accuracy = default(int?), int? invertedAccuracy = default(int?), string source = default(string), string source2 = default(string), bool? isDisabled = default(bool?))
        {
            Id = id;
            Name = name;
            BaseAssetId = baseAssetId;
            QuotingAssetId = quotingAssetId;
            Accuracy = accuracy;
            InvertedAccuracy = invertedAccuracy;
            Source = source;
            Source2 = source2;
            IsDisabled = isDisabled;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseAssetId")]
        public string BaseAssetId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuotingAssetId")]
        public string QuotingAssetId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Accuracy")]
        public int? Accuracy { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InvertedAccuracy")]
        public int? InvertedAccuracy { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Source")]
        public string Source { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Source2")]
        public string Source2 { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsDisabled")]
        public bool? IsDisabled { get; private set; }

    }
}
