// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Assets.Client.Models
{
    using Lykke.Service;
    using Lykke.Service.Assets;
    using Lykke.Service.Assets.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the AssetResponseModel class.
        /// </summary>
        public AssetResponseModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetResponseModel class.
        /// </summary>
        public AssetResponseModel(string id = default(string), string blockChainId = default(string), string blockChainAssetId = default(string), string name = default(string), string symbol = default(string), string idIssuer = default(string), bool? isBase = default(bool?), bool? hideIfZero = default(bool?), int? accuracy = default(int?), double? multiplier = default(double?), bool? isDisabled = default(bool?), bool? hideWithdraw = default(bool?), bool? hideDeposit = default(bool?), int? defaultOrder = default(int?), bool? kycNeeded = default(bool?), string assetAddress = default(string), bool? bankCardsDepositEnabled = default(bool?), bool? swiftDepositEnabled = default(bool?), bool? blockchainDepositEnabled = default(bool?), double? dustLimit = default(double?), string categoryId = default(string))
        {
            Id = id;
            BlockChainId = blockChainId;
            BlockChainAssetId = blockChainAssetId;
            Name = name;
            Symbol = symbol;
            IdIssuer = idIssuer;
            IsBase = isBase;
            HideIfZero = hideIfZero;
            Accuracy = accuracy;
            Multiplier = multiplier;
            IsDisabled = isDisabled;
            HideWithdraw = hideWithdraw;
            HideDeposit = hideDeposit;
            DefaultOrder = defaultOrder;
            KycNeeded = kycNeeded;
            AssetAddress = assetAddress;
            BankCardsDepositEnabled = bankCardsDepositEnabled;
            SwiftDepositEnabled = swiftDepositEnabled;
            BlockchainDepositEnabled = blockchainDepositEnabled;
            DustLimit = dustLimit;
            CategoryId = categoryId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BlockChainId")]
        public string BlockChainId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BlockChainAssetId")]
        public string BlockChainAssetId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Symbol")]
        public string Symbol { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IdIssuer")]
        public string IdIssuer { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsBase")]
        public bool? IsBase { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HideIfZero")]
        public bool? HideIfZero { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Accuracy")]
        public int? Accuracy { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Multiplier")]
        public double? Multiplier { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsDisabled")]
        public bool? IsDisabled { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HideWithdraw")]
        public bool? HideWithdraw { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HideDeposit")]
        public bool? HideDeposit { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DefaultOrder")]
        public int? DefaultOrder { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "KycNeeded")]
        public bool? KycNeeded { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetAddress")]
        public string AssetAddress { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BankCardsDepositEnabled")]
        public bool? BankCardsDepositEnabled { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SwiftDepositEnabled")]
        public bool? SwiftDepositEnabled { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BlockchainDepositEnabled")]
        public bool? BlockchainDepositEnabled { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DustLimit")]
        public double? DustLimit { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CategoryId")]
        public string CategoryId { get; private set; }

    }
}
