// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Assets.Client.Models
{
    using Lykke.Service;
    using Lykke.Service.Assets;
    using Lykke.Service.Assets.Client;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for Blockchain.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Blockchain
    {
        [EnumMember(Value = "None")]
        None,
        [EnumMember(Value = "Bitcoin")]
        Bitcoin,
        [EnumMember(Value = "Ethereum")]
        Ethereum
    }
    internal static class BlockchainEnumExtension
    {
        internal static string ToSerializedValue(this Blockchain? value)  =>
            value == null ? null : ((Blockchain)value).ToSerializedValue();

        internal static string ToSerializedValue(this Blockchain value)
        {
            switch( value )
            {
                case Blockchain.None:
                    return "None";
                case Blockchain.Bitcoin:
                    return "Bitcoin";
                case Blockchain.Ethereum:
                    return "Ethereum";
            }
            return null;
        }

        internal static Blockchain? ParseBlockchain(this string value)
        {
            switch( value )
            {
                case "None":
                    return Blockchain.None;
                case "Bitcoin":
                    return Blockchain.Bitcoin;
                case "Ethereum":
                    return Blockchain.Ethereum;
            }
            return null;
        }
    }
}
