// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Assets.Client.Models
{
    using Lykke.Service;
    using Lykke.Service.Assets;
    using Lykke.Service.Assets.Client;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for Blockchain.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Blockchain
    {
        [EnumMember(Value = "None")]
        None,
        [EnumMember(Value = "Bitcoin")]
        Bitcoin,
        [EnumMember(Value = "Ethereum")]
        Ethereum
    }
}
