// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Assets.Client.Models
{
    using Lykke.Service;
    using Lykke.Service.Assets;
    using Lykke.Service.Assets.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GetAssetPairsForClientRequestModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GetAssetPairsForClientRequestModel class.
        /// </summary>
        public GetAssetPairsForClientRequestModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// GetAssetPairsForClientRequestModel class.
        /// </summary>
        public GetAssetPairsForClientRequestModel(string clientId = default(string), bool? isIosDevice = default(bool?), string partnerId = default(string))
        {
            ClientId = clientId;
            IsIosDevice = isIosDevice;
            PartnerId = partnerId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsIosDevice")]
        public bool? IsIosDevice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartnerId")]
        public string PartnerId { get; set; }

    }
}
