// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Assets.Client.Models
{
    using Lykke.Service;
    using Lykke.Service.Assets;
    using Lykke.Service.Assets.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IAssetCategory
    {
        /// <summary>
        /// Initializes a new instance of the IAssetCategory class.
        /// </summary>
        public IAssetCategory()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IAssetCategory class.
        /// </summary>
        public IAssetCategory(string id = default(string), string name = default(string), string iosIconUrl = default(string), string androidIconUrl = default(string), int? sortOrder = default(int?))
        {
            Id = id;
            Name = name;
            IosIconUrl = iosIconUrl;
            AndroidIconUrl = androidIconUrl;
            SortOrder = sortOrder;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IosIconUrl")]
        public string IosIconUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AndroidIconUrl")]
        public string AndroidIconUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SortOrder")]
        public int? SortOrder { get; set; }

    }
}
