// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Assets.Client.Models
{
    using Lykke.Service;
    using Lykke.Service.Assets;
    using Lykke.Service.Assets.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IAssetDescription
    {
        /// <summary>
        /// Initializes a new instance of the IAssetDescription class.
        /// </summary>
        public IAssetDescription()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IAssetDescription class.
        /// </summary>
        public IAssetDescription(string id = default(string), string assetId = default(string), string assetClass = default(string), string description = default(string), string issuerName = default(string), string numberOfCoins = default(string), string marketCapitalization = default(string), int? popIndex = default(int?), string assetDescriptionUrl = default(string), string fullName = default(string))
        {
            Id = id;
            AssetId = assetId;
            AssetClass = assetClass;
            Description = description;
            IssuerName = issuerName;
            NumberOfCoins = numberOfCoins;
            MarketCapitalization = marketCapitalization;
            PopIndex = popIndex;
            AssetDescriptionUrl = assetDescriptionUrl;
            FullName = fullName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetClass")]
        public string AssetClass { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IssuerName")]
        public string IssuerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NumberOfCoins")]
        public string NumberOfCoins { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MarketCapitalization")]
        public string MarketCapitalization { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PopIndex")]
        public int? PopIndex { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetDescriptionUrl")]
        public string AssetDescriptionUrl { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FullName")]
        public string FullName { get; private set; }

    }
}
