name: CI dev build

on:
  push:
      branches:
        - dev-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=0.0.0
    - name: Test
      run: dotnet test --no-build --configuration Release

    - name: Publish Service
      run: dotnet publish --no-build ./src/Lykke.Service.Assets/Lykke.Service.Assets.csproj --configuration Release --output ./publish-api

    - name: Check Service dir
      run: ls ./publish-api

    - name: Publish Manager API to registry
      uses: swisschain/Publish-Docker-Github-Action@master
      with:
        name: swisschains/antares-service-assets:dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./publish-api
        # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
        tag_names: true
    - name: Restart service
      uses: swisschain/kube-restart-pods@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.LYKKE_DEV_KUBE_CONFIG_DATA }}
        NAMESPACE: lykke-service
        POD: assets