name: CI test build

on:
  push:
      branches:
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.103
    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=0.0.0
    - name: Test
      run: dotnet test --no-build --configuration Release

    - name: Publish Service
      run: dotnet publish --no-build ./src/Lykke.Service.Assets/Lykke.Service.Assets.csproj --configuration Release 

    - name: Check Service dir
      run: ls ./src/Lykke.Service.Assets/bin/Release/netcoreapp2.1/publish

    - name: Publish Manager API to registry
      uses: swisschain/Publish-Docker-Github-Action@master
      with:
        name: swisschains/antares-service-asset:test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./src/Lykke.Service.Assets/bin/Release/netcoreapp2.1/publish
        # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
        tag_names: true